volumes:
  postgres_data:

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
