---
- hosts: all
  become: yes
  vars:
    postgres_version: 16
    # pgdg_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    pgdg_key_url: https://mirrors.aliyun.com/postgresql/repos/apt/ACCC4CF8.asc
    # pgdg_repo_url: https://apt.postgresql.org/pub/repos/apt
    pgdg_repo_url: https://mirrors.aliyun.com/postgresql/repos/apt/
    pgdg_key_path: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
    
   
  
  handlers:
    - name: restart postgresql
      service: name=postgresql@16-main.service state=restarted

  tasks:
    - name: create postgresql-common directory
      file:
        path: "{{ pgdg_key_path | dirname }}"
        state: directory
        mode: '0755'

    - name : add postgresql key
      get_url:
        url: "{{ pgdg_key_url }}"
        dest: "{{ pgdg_key_path }}"

    - name : add postgresql repo
      apt_repository:
        repo: deb [signed-by={{ pgdg_key_path }}] {{ pgdg_repo_url }} {{ ansible_distribution_release }}-pgdg main
        state: present
        filename: pgdg

    - name: install postgresql
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - "postgresql-{{ postgres_version }}"
        - "postgresql-client-{{ postgres_version }}"
        - libpq-dev
        - python3-psycopg2

  