---
- hosts: all
  vars:
    postgres_db_user: hey8
    postgres_db_password: "password"
    postgres_db_name: app_production

  tasks:
    - name: install community.postgresql Requirements
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3-psycopg2
        - acl
    - block:
      - name: Create PostgreSQL user
        community.postgresql.postgresql_user:
          name: "{{ postgres_db_user }}"
          password: "{{ postgres_db_password }}"
          role_attr_flags: 'CREATEDB'
          state: present

      - name: Create PostgreSQL database
        community.postgresql.postgresql_db:
          name: "{{ postgres_db_name }}"
          owner: "{{ postgres_db_user }}"
          state: present

      # 需要切换到 postgres 用户，因为其他用户操作不了
      become: true
      become_user: postgres